### ISSUE TITLE
Still have ads after patching

### ISSUE THREAD

**Issue by meichengg** [ReVanced/revanced-patches-template#125]
On the latest versions of patches, integrations, cli, after building to Revanced APK and got it installed on my phone, ads still appear. Sometimes, i must wait for 3 ads to finish to get to watch the video. I use this to build APK [https://github.com/reisxd/revanced-builder](https://github.com/reisxd/revanced-builder).

Youtube version: **17.25.34**

![IMG_20220707_113052](https://user-images.githubusercontent.com/25204246/177692369-10d6161e-2734-41cb-a059-5ff9f6aed324.jpg)

**Comment by streetsamurai00mi** [comment]
> I use this to build APK https://github.com/reisxd/revanced-builder.

First of all you should read [revanced-documentation](https://github.com/revanced/revanced-documentation) and build it manually

**Comment by TheJeterLP** [comment]
Not reproducable for me. Don't use tools to build ReVanced which we do not support.

**Comment by TheJeterLP** [comment]
Also wrong place. Please use the discussions for this.
