### ISSUE TITLE
bug: YouTube videos stop playing after 30 seconds

### ISSUE THREAD

**Issue by theofficialgman** [ReVanced/revanced-patches-template#1730]
### Type

Error at runtime

### Bug description

Starting about 2-3 weeks ago YouTube videos would stop playing after about the first 20-30 seconds and will infinitely buffer. 

This did not happen on previous versions and seems to have been a change on YouTubes end (maybe they implemented some sort of server side detection).

Reinstalling and repatching does not fix it. The regular YouTube app does not display these issues.

### Steps to reproduce

Install v18.03.36 of YouTube.
Patch with non-root (spoof app version, video ads, microg, etc)
Play any video

### Relevant log output

```shell
None
```

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by reisxd** [comment]
Acknowledgements not met (dupe).

**Comment by theofficialgman** [comment]
@reisxd umm no this is not a dupe. I search 3 months back of issues and did not see this reported. Please reopen or link the duplicated issue

**Comment by reisxd** [comment]
> @reisxd umm no this is not a dupe. I search 3 months back of issues and did not see this reported. Please reopen or link the duplicated issue 

#981

**Comment by Xyur1** [comment]
> Acknowledgements not met (dupe).

what do you mean?

**Comment by theofficialgman** [comment]
@reisxd I would appreciate a bug remaining OPEN at this repo even if it is an upstream problem.

Users typically don't search for closed bug reports as that usually indicates that the bug has been fixed.
At my own repos I keep the bug open and add a tag "Upstream Bug"

https://github.com/microg/GmsCore/issues/1870

**Comment by reisxd** [comment]
> @reisxd I would appreciate a bug remaining OPEN at this repo even if it is an upstream problem.
> 
> Users typically don't search for closed bug reports as that usually indicates that the bug has been fixed which it has not.
> At my own repos I keep the bug open and add a tag "Upstream Bug"
> 
> https://github.com/microg/GmsCore/issues/1870

Their fault for not searching properly. Also, the issue has been fixed.

**Comment by oSumAtrIX** [comment]
This issue is deprecated in favour of https://github.com/revanced/revanced-patches/issues/1752.

**Comment by Cartman34** [comment]
I am experiencing the same issue with YT Revanced and i did not find any workaround here...
Please, could you explicitly tell us what to do to fix it ? With details ?

Something new happened, I updated MicroG (idk if this improved the situation...) and now the video is buffering, then stop, buffer another part of the video (the video is still stopped), then play it, then stop... There is no more continuous buffering, this is very annoying.

**Comment by oSumAtrIX** [comment]
Neither revanced.io nor revanced.net are from us.
