### ISSUE TITLE
Unlock Telegram Premium

### ISSUE THREAD

**Issue by Qaz-7** [ReVanced/revanced-patches-template#1829]
### Application

Telegram

### Issue

Unlock Telegram Premium features.

### Patch

Unlock premium features without subscribing to Telegram Premium

![Screenshot_20230401-090801_Telegram](https://user-images.githubusercontent.com/124310688/229266794-73f18113-7670-4f79-9fce-c9a348cded40.jpg)

### Motivation

Because, all the mod apks on the Internet are fake. Also, Telegram Premium offers many functions

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by wolf-yuan-6115** [comment]
I don't think it will work, if you are looking for faster download speed, you can try MDgram

**Comment by Qaz-7** [comment]
Premium features can be unlocked.

**Comment by reisxd** [comment]
The premium features are server-sided, not client sided.

**Comment by Qaz-7** [comment]
MDgram does not offer all features.

**Comment by oSumAtrIX** [comment]
Closing due to being locked by server.

**Comment by Qaz-7** [comment]
Subscribe to Telegram Premium and modify the Apk.

**Comment by oSumAtrIX** [comment]
Works without modifying the app 👍

**Comment by Qaz-7** [comment]
You subscribe to unlock.You modify and share that APK.
