### ISSUE TITLE
feat: Add old resolution picker for videos

### ISSUE THREAD

**Issue by kairusds** [ReVanced/revanced-patches-template#184]
## 🐞 Issue

The current resolution picker for youtube is cluttered and you need to go to the "Advanced" menu to change it manually.

## ❗ Solution

Revert this option by only showing the actual resolutions.

## ❓ Motivation

Most people would not notice that their video has dropped in quality and the current resolution picker chooses it randomly.

**Comment by bogadana** [comment]
1. wrong place
2. check existing patches before suggesting

**Comment by anyz0** [comment]
this patch already exist, but still buggy

**Comment by TheJeterLP** [comment]
> this patch already exist, but still buggy

It's not buggy, it broke.on the new YouTube version because Google changed something there. Still works perfectly on older versions.

**Comment by kairusds** [comment]
Isn't it possible to modify the UI itself though instead of relying on a removed internal function?

**Comment by oSumAtrIX** [comment]
Please move to the discussions
