### ISSUE TITLE
feat(youtube): change default video sort order to 'sort by latest'

### ISSUE THREAD

**Issue by Shane9248** [ReVanced/revanced-patches-template#1862]
### Application

YouTube ReVanced

### Issue

![Screenshot_20230406-110244~2](https://user-images.githubusercontent.com/83491863/230281386-f3d37c9c-2deb-4323-8ebe-380d29eef96a.png)

When u open the videos section of a channel it always sorts the videos by 'FOR u' fitler 

### Patch

It would be really helpful if we can get a option to always show videos by 'LATEST' filter by default so that we don't have to manually select the option everytime 

### Motivation

It makes the UX way better

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Shane9248** [comment]
> I have never seen thay "for you" button before! Does it appear on every channel? 

yes it is on every channel ..only just popped up a couple of days ago on official yt app too

**Comment by EhabxAlaa** [comment]
> > I have never seen thay "for you" button before! Does it appear on every channel?
> 
> yes it is on every channel ..only just popped up a couple of days ago on official yt app too

It doesn't appear for me, maybe it will pop up for me later but for now I only have to ways to sort videos, and that "for you " button sounds weird and i don't want it too

**Comment by Shane9248** [comment]
> > > I have never seen thay "for you" button before! Does it appear on every channel?
> > 
> > yes it is on every channel ..only just popped up a couple of days ago on official yt app too
> 
> It doesn't appear for me, maybe it will pop up for me later but for now I only have to ways to sort videos, and that "for you " button sounds weird and i don't want it too

google never fails to impress ..what really useful would be to bring back the sort by OLDEST filter instead they bring this which makes videos order completely random 🤷🏻‍♂️

**Comment by EhabxAlaa** [comment]
> google never fails to impress ..what really useful would be to bring back the sort by OLDEST filter instead they bring this which makes videos order completely random 🤷🏻‍♂️
Exactly, we need sort by oldest back , the only reason i still have vanced is so i can use it

**Comment by genesisrhapsodos98** [comment]
This has been a major annoyance for me for the past few weeks too. Hopefully there's a patch for it soon.
