### ISSUE TITLE
Sudden infinite buffering after watching for some time

### ISSUE THREAD

**Issue by muchisx** [ReVanced/revanced-patches-template#1890]
### Type

Error at runtime

### Bug description

During playback, after a random amount of time, the video stops playing and shows a loading circle (as if connection was lost), the player never reconnects and it gets stuck in an infinite loading/buffering black screen.

### Steps to reproduce

1. Play any video (better if its a long one, 10+min)
2. Wait
3. Infinite loading/buffer will appear randomly

### Relevant log output

```shell
It doesn't crash
```

### Solution

There are a bunch of posts in reddit r/revancedapp outlining the same issue

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
#1752

**Comment by oSumAtrIX** [comment]
Yes I am certain.

**Comment by oSumAtrIX** [comment]
You likely also did something wrong as playback is working once the fix is applied.

**Comment by Elias-Graf** [comment]
> You likely also did something wrong as playback is working once the fix is applied.

@oSumAtrIX I patched the app a few days ago, everything worked. It stopped working a few hours ago. I'm 100% certain. I repatched the app today woth the latest release, same result.

**Comment by oSumAtrIX** [comment]
In that case please send a full recording of the following:

1. Close & open ReVanced Manager
2. Patch YouTube
4. Open it & showcase the issue

**Comment by Nathanwoodburn** [comment]
I'm having the same issue. The last time I patched it was over 6 months ago. It just stopped working today. I've repatched it and still doesn't work. It will just start buffering

**Comment by Loadren** [comment]
Same error here.

Just repatched on 18.05.40 with :
`java -jar revanced-cli.jar -a youtube.apk -b revanced-patches.jar -i client-spoof -i custom-branding -i custom-video-speed  -i disable-auto-captions -i disable-player-popup-panels -i disable-shorts-on-startup -i downloads -i enable-wide-searchbar -i general-ads -i hide-floating-microphone-button -i microg-support -i minimized-playback -i remember-video-quality -i return-youtube-dislike -i sponsorblock -i theme -i video-ads -o Revanced.apk --exclusive -m int.apk`

Seems like it stops working after some time (~30 sec or 1 min) and keeps buffering. It also happens on Home Screen with autoplay.

https://user-images.githubusercontent.com/23261689/231744388-61e3aac2-cd8e-4c73-9431-fce8da933a30.mp4

**Comment by marcelalani** [comment]
> I'm having the same issue. The last time I patched it was over 6 months ago. It just stopped working today. I've repatched it and still doesn't work. It will just start buffering

Patch a new apk with the "spoof signature verification" patch, make sure the setting is on in the app once it's done. This fixed the issue for me.
![Screenshot_20230413_232541](https://user-images.githubusercontent.com/8307088/231744758-355e6515-0d03-422b-b83e-f7b40ba864e6.jpg)
![Screenshot_20230413_232703](https://user-images.githubusercontent.com/8307088/231744996-bff352fc-d5ca-4e8e-b3ad-fc7f02c08d1a.jpg)
