### ISSUE TITLE
bug(YouTube): app is displaying SettingsEnum toast error message

### ISSUE THREAD

**Issue by Yanagawakakogawak** [ReVanced/revanced-patches-template#1935]
### Type

Error at runtime

### Bug description

Keep getting Error: SettingsEnum: Error while trying to update dislikes

### Steps to reproduce

Keep getting Error: SettingsEnum: Error while trying to update dislikes

### Relevant log output

```shell
Keep getting Error: SettingsEnum: Error while trying to update dislikes
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by michelkluger** [comment]
Issue still happening on OnePlus 9, latest app version of revanced

**Comment by TheyTookUrrJaaabs** [comment]
![Screenshot_20230520_063850](https://github.com/revanced/revanced-patches/assets/134108904/d492004c-712a-4aa9-b8ca-46c915a4a465)

**Comment by MsVron** [comment]
I have the same issue and i have everything updated
