### ISSUE TITLE
feat(patch): Unlimited Google Photos Storage at Original Quality

### ISSUE THREAD

**Issue by itsyourap** [ReVanced/revanced-patches-template#2144]
### Application

Google Photos (com.google.android.apps.photos)

### Issue

This patch will enable unlimited storage at original quality in Google Photos.

### Patch

1. Integrate Vanced MicroG into Google Photos
2. Hook `android.app.ApplicationPackageManager.hasSystemFeature(String)` and `android.app.ApplicationPackageManager.hasSystemFeature(String, int)` to return true when some feature flags validity is checked by Google Photos. (As far as know, Google uses a compiled library to call the method, so we cannot modify it since it is not bytecode)

Although, we can use Frida to hook the `android.app.ApplicationPackageManager.hasSystemFeature(String)` method and return true whenever these arguments are passed:-
1. `com.google.android.apps.photos.NEXUS_PRELOAD`
2. `com.google.android.apps.photos.nexus_preload`
3. `com.google.android.feature.PIXEL_EXPERIENCE`
4. `com.google.android.apps.photos.PIXEL_PRELOAD`
5. `com.google.android.apps.photos.PIXEL_2016_PRELOAD`

We can easily integrate `frida-gadget` into the app to hook the method. (I can do this part)

When `android.app.ApplicationPackageManager.hasSystemFeature(String)` returns true for these arguments, Google Photos provides unlimited storage at Original Quality for no cost. I have already created a Frida script that works for this but I could only test it on rooted devices since for non rooted, Google Photos won't get access to Google Account due to Signature Mismatch. Thats why I am requesting to integrate Vanced MicroG into Google Photos. Also, I can share the Frida Script if you like.

Also, maybe we can get access to Google One features using this.

### Motivation

This patch will enable users to get Unlimited Google Photos Storage at Original Quality, which is desired by a lot of people.
Also, tinkering with this patch a bit more might enable Google One features for Google Photos

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AwesomeParley** [comment]
Does the Frida script actually not take up space? I remember having this option a long time ago, but they since discontinued it and I had to clear my entire google account of photos due to it having over 20GB of storage being used all of a sudden. I had just assumed this was server-side, but now I am curious.

**Comment by itsyourap** [comment]
I am using the root version of it for over a year now. There hasn't been any problems.
[Pixelify-Google-Photos](https://github.com/BaltiApps/Pixelify-Google-Photos) does the same using Xposed/LSPosed Framework on rooted devices/

**Comment by itsyourap** [comment]
As for proof, these are some screenshots I would like to share :-

![image](https://github.com/revanced/revanced-patches/assets/90060131/6259b44b-e2ae-42f6-8d8f-ee935ca8b105)
![image](https://github.com/revanced/revanced-patches/assets/90060131/c88adbda-55ef-4494-9437-d3c2e7b0024d)

**Comment by AwesomeParley** [comment]
> I am using the root version of it for over a year now. There hasn't been any problems.
> [Pixelify-Google-Photos](https://github.com/BaltiApps/Pixelify-Google-Photos) does the same using Xposed/LSPosed Framework on rooted devices/

Ah I understand how it works now. So basically it's just telling Google "Hey, I'm a Google Pixel, so allow this user to upload Unlimited Google Photos" and then it just does. 

Interesting. I do wonder how Vanced MicroG would work with that or if it even can since it's not managed by Revanced. I bet some smart people could figure it out.

**Comment by itsyourap** [comment]
Yes! Thats how it works. Vanced MicroG will just provide access to the Google Account instead of the original `com.google.gms` to bypass the signature detection. (The same with YouTube Revanced)

**Comment by AlyafeiAli** [comment]
> As for proof, these are some screenshots I would like to share :-
> 
> ![image](https://user-images.githubusercontent.com/90060131/238166905-6259b44b-e2ae-42f6-8d8f-ee935ca8b105.png) ![image](https://user-images.githubusercontent.com/90060131/238166914-c88adbda-55ef-4494-9437-d3c2e7b0024d.png)
> 
> These screenshots are taken from a non Google Device. BTW, This also works on emulators. (Tried and tested ✅)

Interesting. What emulator did you use?

**Comment by itsyourap** [comment]
> Interesting. What emulator did you use?

I used LDPlayer and installed Magisk Delta in its `/system` partition, enabled Zygisk and flashed LSPosed-Zygisk module and then used [Pixelify-Google-Photos](https://github.com/BaltiApps/Pixelify-Google-Photos) module to achieve this.

Instead of using this method, you can also use Frida with root access to hook into the above mentioned methods to achieve the same.

**Comment by AlyafeiAli** [comment]
> As for proof, these are some screenshots I would like to share :-
> 
> ![image](https://user-images.githubusercontent.com/90060131/238166905-6259b44b-e2ae-42f6-8d8f-ee935ca8b105.png) ![image](https://user-images.githubusercontent.com/90060131/238166914-c88adbda-55ef-4494-9437-d3c2e7b0024d.png)
> 
> These screenshots are taken from a non Google Device. BTW, This also works on emulators. (Tried and tested ✅)

Interesting. What emulator did you use?

> > Interesting. What emulator did you use?
> 
> I used LDPlayer and installed Magisk Delta in its `/system` partition, enabled Zygisk and flashed LSPosed-Zygisk module and then used [Pixelify-Google-Photos](https://github.com/BaltiApps/Pixelify-Google-Photos) module to achieve this.
> 
> Instead of using this method, you can also use Frida with root access to hook into the above mentioned methods to achieve the same.

Thank you for the detailed explanation, I appreciate it 😄

**Comment by AlyafeiAli** [comment]
btw, @itsyourap , do you mind sharing the Frida script you created so we can test it as well?

**Comment by itsyourap** [comment]
> btw, @itsyourap , do you mind sharing the Frida script you created so we can test it as well?

Sure! Here you go:-

```js
function getClassFactory(className) {
    let classFactory;
    const classLoaders = Java.enumerateClassLoadersSync();
    for (const classLoader in classLoaders) {
        try {
            classLoaders[classLoader].findClass(className);
            classFactory = Java.ClassFactory.get(classLoaders[classLoader]);
            break;

        } catch (e) {
             // Some Error Occurred
        }
    }
    return classFactory;
}

function hookBuildVariables() {
    const buildClass = Java.use('android.os.Build');
    buildClass.BRAND.value = "google";
    buildClass.MANUFACTURER.value = "Google";
    buildClass.DEVICE.value = "marlin";
    buildClass.PRODUCT.value = "marlin";
    buildClass.MODEL.value = "Pixel XL";
    buildClass.FINGERPRINT.value = "google/marlin/marlin:10/QP1A.191005.007.A3/5972272:user/release-keys";
    console.log('Hooked Build Variables');
}

function hookHasSystemFeature() {
    const className = "android.app.ApplicationPackageManager";
    const classFactory = getClassFactory(className);
    const pmClass = classFactory.use(className);
    const hasSystemFeatureMethod = pmClass.hasSystemFeature;

    hasSystemFeatureMethod.overload('java.lang.String').implementation = function (featureName) {
        console.log(`hasSystemFeature(String) called with featureName : ${featureName}`);

        if (featureName == "com.google.android.apps.photos.NEXUS_PRELOAD"
            || featureName == "com.google.android.apps.photos.nexus_preload"
            || featureName == "com.google.android.feature.PIXEL_EXPERIENCE"
            || featureName == "com.google.android.apps.photos.PIXEL_PRELOAD"
            || featureName == "com.google.android.apps.photos.PIXEL_2016_PRELOAD") {
            return true;
        }

        const result = hasSystemFeatureMethod.call(this, featureName);
        console.log(`Result : ${result}`)
        return result;
    }

    hasSystemFeatureMethod.overload('java.lang.String', 'int').implementation = function (featureName, version) {
        console.log(`hasSystemFeature(String) called with featureName : ${featureName} and version : ${version}`);

        if (featureName == "com.google.android.apps.photos.NEXUS_PRELOAD"
            || featureName == "com.google.android.apps.photos.nexus_preload"
            || featureName == "com.google.android.feature.PIXEL_EXPERIENCE"
            || featureName == "com.google.android.apps.photos.PIXEL_PRELOAD"
            || featureName == "com.google.android.apps.photos.PIXEL_2016_PRELOAD") {
            return true;
        }

        const result = hasSystemFeatureMethod.call(this, featureName, version);
        console.log(`Result : ${result}`)
        return result;
    }

    console.log('Hooked hasSystemFeature method');
}


function main() {
    hookBuildVariables();
    hookHasSystemFeature();
}

Java.perform(() => {
    main();
});
```

**Comment by AlyafeiAli** [comment]
> This script spoofs your device as Pixel XL 2016 to Google Photos. This gives us Unlimited Google Photos Storage at Original Quality.

Much appreciated, thanks!

**Comment by AlyafeiAli** [comment]
I can confirm that the Frida script is working perfectly!

![image](https://github.com/revanced/revanced-patches/assets/52626961/552ddafe-0680-4075-b154-69ea05f0c3db)

**Comment by itsyourap** [comment]
Yes! We can use this on non-rooted devices by integrating `frida-gadget` into Google Photos apk, but someone has to integrate Vanced MicroG into it to evade signature detection.

**Comment by oSumAtrIX** [comment]
#2036

**Comment by itsyourap** [comment]
Can we get an ETA when this patch might arrive?

**Comment by nochlab1** [comment]
Is there any chance of this happening any time soon?

**Comment by XdekHckr** [comment]
why it was rejected from development tho?

**Comment by RivelBop** [comment]
I would love to see this be integrated, I hope that they won't give up on this idea!

**Comment by mountaser** [comment]
> I can confirm that the Frida script is working perfectly!
> 
> ![image](https://user-images.githubusercontent.com/52626961/238181239-552ddafe-0680-4075-b154-69ea05f0c3db.png)
> 
> ![image](https://user-images.githubusercontent.com/52626961/238181292-fc5c894f-da34-4829-8bda-943bba56e9c0.png)
@itsyourap  would one of you be nice enough to explain how use the frida script?
and also @itsyourap is it possible to change the app name so i can have a modded and none mooded apps installed togather? reason is i have a p8p and i assume if the app thinks its a pixel 1 i wont get the magic editor and other features from the pixel 8 pro

**Comment by nochlab1** [comment]
> > I can confirm that the Frida script is working perfectly!
> > ![image](https://user-images.githubusercontent.com/52626961/238181239-552ddafe-0680-4075-b154-69ea05f0c3db.png)
> > ![image](https://user-images.githubusercontent.com/52626961/238181292-fc5c894f-da34-4829-8bda-943bba56e9c0.png)
> > @itsyourap  would one of you be nice enough to explain how use the frida script?
> > and also @itsyourap is it possible to change the app name so i can have a modded and none mooded apps installed togather? reason is i have a p8p and i assume if the app thinks its a pixel 1 i wont get the magic editor and other features from the pixel 8 pro

Yes we know that but we want it on a non rooted phone

**Comment by kunal266** [comment]
yes is it possible to use this frida script with a non-rooted phone

**Comment by gerryave** [comment]
Hi everyone, I'm looking for an apk file modified with Frida. It's the first time I've tried to mod with Frida and I can't. I don't understand where I'm going wrong. Would it be possible for some of you to help me or send me an apk modified with Frida so I can have google photos? unlimited on my non-rooted device?

**Comment by oSumAtrIX** [comment]
This is not a support channel, we get notified about new comments here; please move to one of our other platforms you can find on https://revanced.app
