### ISSUE TITLE
bug: Revanced crashes when I try to run it.

### ISSUE THREAD

**Issue by aryanmaulana7636** [ReVanced/revanced-patches-template#2212]
### Type

Error while patching

### Bug description

When I try run revanced, it's crashing, which very annoyed,

### Steps to reproduce

Step 1 try run revanced
Step 2 crash.

### Relevant log output

```shell
No
```

### Solution

none

### Additional context

I using dev version 

### Acknowledgements

- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by aryanmaulana7636** [comment]
Why it's closed?

**Comment by reisxd** [comment]
> Why it's closed?

Because the acknowledgements are not met.

**Comment by EhabxAlaa** [comment]
> Why it's closed?

You gave absolutely no information and you expect it to not be closed?! Like no apk version or device specs or patches used or anything
