### ISSUE TITLE
bug(youtube):Update screen pops up when I spoof app version

### ISSUE THREAD

**Issue by Techfromthepast123** [ReVanced/revanced-patches-template#2388]
### Type

Error while patching

### Bug description

When I spoof my youtube version using the spoof patch,it show an update screen telling me to update Youtube to the latest version.

### Steps to reproduce

Step 1.Go to youtube revanced Step 2.enable spoof version patch to any version Step 3.relaunch youtube and the fullscreen update screen with the robot will show up.

### Relevant log output

```shell
Idk any log outputs
```

### Screenshots or videos

![Screenshot_20230611-093337](https://github.com/revanced/revanced-patches/assets/112059671/f2d4f148-b894-472c-97bf-7e2534d5d192)

### Solution

Idk if it's possible but if youtube killed the old versions of youtube apps (explorer on nav bar,old UI,old shorts player) maybe revanced should create a patch that makes the current UI look like the old one. (With old channel page,shorts,etc...)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Techfromthepast123** [comment]
No I am using  18.16.37

**Comment by Techfromthepast123** [comment]
I tried to patch the 18.19.35 apk with cmd (on PC) but it says that the patches such has spoof app version or vanced microg support are not compatible with version 18.19.35.

**Comment by oSumAtrIX** [comment]
18.16 is not supported by any current patch

**Comment by Techfromthepast123** [comment]
How do I update to the latest 2.175.0 patches ?

Also does this mean the updated spoof app version patch remove the update screens ?

**Comment by Techfromthepast123** [comment]
Oooh okay thanks will do tomorrow !!!

**Comment by Techfromthepast123** [comment]
Ok so I tried it and for some reason it shows his ?:
![Capture d'écran 2023-06-11 195551](https://github.com/revanced/revanced-patches/assets/112059671/8b5ee017-923c-4667-973d-b2ac102ae857)

**Comment by Techfromthepast123** [comment]
And yes I did replace the outdated patch version with the new ones

**Comment by Techfromthepast123** [comment]
NVM it still show that random screen instead of patching

**Comment by Techfromthepast123** [comment]
Pls help me how to make this screen NOT show up

Also what is the patch that makes the youtube player bar white on dark mode back to red like it was on the old youtube layout ?
the spoof app version does not modify the player bar s color

**Comment by oSumAtrIX** [comment]
This is not a support thread. Open a new issue and include a full recording of the issue by using ReVanced Manager to patch the app
