### ISSUE TITLE
bug(youtube): videos only buffer to 1:10, client-spoofing fails

### ISSUE THREAD

**Issue by suptower** [ReVanced/revanced-patches-template#2432]
### Type

Error at runtime

### Bug description

When watching any video, it will stop loading exactly at the 1:09 / 1:10 mark. The issue seems to be related to client-spoofing.

Additionally, spoofing the version to 16.08.35 seems to resolve the problem, as well as activating Incognito.

Theory was this is the result of A/B testing, however, according to this discord thread, it is not only a certain region impacted.
https://discord.com/channels/952946952348270622/1118066503779098684

### Steps to reproduce

1. Have an impacted account.
2. Play any video longer than 70 seconds
3. Try to pass the 1:09 / 1:10 mark. Either by letting the video play or by scrolling (scrolling past this point results in an infinite buffer loop as well)

### Relevant log output

```shell
NA
```

### Screenshots or videos

![image](https://github.com/revanced/revanced-patches/assets/70473844/2ddc54d5-7401-4919-8481-1ca50c86e3ac)

### Solution

 - Spoofing the version to 16.08.35 seems to resolve the problem.
 -  Activate incognito mode

### Additional context

https://discord.com/channels/952946952348270622/1118066503779098684

Spoof App Signature was initially enabled. Tested it with both off and on after the issue has happened, did not alter the outcome.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
> Spoofing the version to 16.08.35 seems to resolve the problem.

Can you try any later versions?

**Comment by oSumAtrIX** [comment]
It may also be that the server reacts differently to the versions. If the server receives one version it does allow playback, if another, it doesn't.

**Comment by suptower** [comment]
I've also tried it with different versions of YouTube Revanced (18.22.36 and 18.19.35). Currently running 18.22.36 with spoofed 16.08.35, which seems to work for now.

**Comment by Julius8900** [comment]
May I know how you did try 18.22.36? The `client-spoof` patch is supported only on version 18.19.35.

**Comment by suptower** [comment]
I've enabled experimental patches support in the settings of Revanced Manager. 

I was keen on having the new UI while simultaneously being able to use SponsorBlock, that's why.
Never ran into issues regarding that and I've been using it for over a month or so I think.

**Comment by kevinbbbb** [comment]
I had the same problem. I solved it like this within the Revanced Youtube App: Settings > ReVanced > Misc > DISABLE Spoof app signature (this was enabled before in my case).
After I disabled it, I can now go past the 1:10min mark again.
Tried with app version 18.19.35.

**Comment by Deathstr0** [comment]
Issue might be related to accounts instead of app. Added a old Gmail id that's not been used to watch videos on both YouTube and revanced. That allows me to watch the same video beyond the 1:10 min mark

**Comment by Darellku** [comment]
> Issue might be related to accounts instead of app. Added a old Gmail id that's not been used to watch videos on both YouTube and revanced. That allows me to watch the same video beyond the 1:10 min mark

yes and no, i tried on different account under the same email :
account 1 with revanced 18.19.35 = doesn't work
account 1 normal app/web/revanced 16.08.35 = works
account 2 works on both the latest revanced or normal youtube

**Comment by suptower** [comment]
It is kinda related to accounts (because incognito mode works in newest versions), but using the regular youtube app, there is no sign of that, since videos play flawlessly there.

**Comment by ASmallSquishySquid** [comment]
I'm also having the same issue with one of my accounts using Revanced with YouTube versions 18.19.35 and 17.17.37(?). However, turning off "spoof app signature" actually fixes the issue for me. This is weird, because previous threads I've seen on this issue state that turning on this setting is intended to fix this exact issue.

**Comment by oSumAtrIX** [comment]
Turning it off won't fix the issue. Anyways don't spam this issue with "me too" or <i have tried the same and it worked/didnt work> comments

**Comment by kitadai31** [comment]
Spoofing to 16.42.38 also worked.
16.42.xx -> works
16.43.xx -> doesn't work

To spoof to 16.42.xx, you can use ＠LisoUseInAIKyrios's method above.

**Comment by ReveLovy** [comment]
using 18.05.40 playback issue when turn on spoofing app signature. Want to keep turned off. But app keeps turn on that option.

**Comment by oSumAtrIX** [comment]
Fixed with https://github.com/revanced/revanced-integrations/commit/be9c948ce6135ec7fad4d7e7dc18be64e9dbb3eb
