### ISSUE TITLE
bug: Thumbnails preview in player not working

### ISSUE THREAD

**Issue by 54m4d** [ReVanced/revanced-patches-template#2523]
### Type

Other

### Bug description

Thumbnails preview in player when seeking back and forth got broken in the last 2 days when spoof app signature is on, when spoof app signature is off, thumbnails work as expected.

### Steps to reproduce

Try to seek back and forth on any video while spoof app signature is on, and try again when it's turned off to see the difference.

### Relevant log output

```shell
NA
```

### Screenshots or videos

<details>
<summary>Spoof app signature On</summary>
<img src=https://github.com/revanced/revanced-patches/assets/52612348/636a33d1-5588-42bb-aa5f-6aa66cdd11e5>
</details>

<details>
<summary>Spoof app signature Off</summary>
<img src=https://github.com/revanced/revanced-patches/assets/52612348/2fae094a-3a62-43a9-9266-03e235b7ff18>
</details>

### Solution

Turn off spoof app signature

### Additional context

S20 Android 13

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 54m4d** [comment]
Can you provide more details rather than just close issues as you always do?

**Comment by 54m4d** [comment]
But i have never experienced this before.

Also, when we turn spoof app signature off, it turns itself back on automatically, how can we prevent this so we can be able to see the thumbnails again?

**Comment by 54m4d** [comment]
Ok, at least we have some explanation of what's the issue about, thanks.

**Comment by oSumAtrIX** [comment]
This information is the other issue you ignored when ticking the first acknowledgment.

**Comment by 54m4d** [comment]
I have searched, but since the wording is different it was not matched, so i couldn't find that issue.

**Comment by oSumAtrIX** [comment]
![image](https://github.com/revanced/revanced-patches/assets/13122796/82cdb4e9-75a4-4789-a7ca-0e008211b298)

**Comment by 54m4d** [comment]
Yep i can see it now, maybe i missed some word or something, i think i searched video player thumbnail or something like that, but in general the search is a hit and miss.
