### ISSUE TITLE
feat: Official Reddit App Enhancments (Restore Top/Hot/New for Front Page, Full Cards & Move Upvote Button to the right side)

### ISSUE THREAD

**Issue by Kristijan1001** [ReVanced/revanced-patches-template#2547]
### Application

Reddit

### Issue

1. Move reddit upvote button.
Can't reach left side upvote button one handed. Custom reddit clients are going away so this is the way. This used to be Reddit+ Feature for iOS back in the day.

2. Expand the card view list to show the full image and extend to the side of the screen instead of having rounded corners.

3. Bring back the New/Hot/Top sorting for the homepage/front page.

### Patch

1. Move upvote button to bottom right of posts.
2. Expand and Extend Cards to show full image, also removing the rounded cards and extending them to the edge of the screen.
3. Bring Back the frontpage Top/Hot/New sort options.

### Motivation

Because custom clients are going away.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Julius8900** [comment]
#1182

**Comment by Kristijan1001** [comment]
> #1182

Those are diffrent so why is this being closed?

**Comment by Julius8900** [comment]
There is already an issue which lists some features that can be added. If you want to add suggestions by yourself, add them to that issue, don't open another one.

**Comment by Kristijan1001** [comment]
> There is already an issue which lists some features that can be added. If you want to add suggestions by yourself, add them to that issue, don't open another one.

But that makes no sense, u link an issue from 2022 that has been dead in the water. If the same rule applies they shouldnt everything be in one thread, yet there are tons of reddit stuff on the issue page. My issues and future requests have nothing to do with that guy nor are any simillar.

**Comment by oSumAtrIX** [comment]
The issue is not dead and open.
