### ISSUE TITLE
bug: Sync for Reddit 'disable-ads' patch failed

### ISSUE THREAD

**Issue by Sherman-Liu** [ReVanced/revanced-patches-template#2549]
### Type

Error while patching

### Bug description

I tried to patch Sync for Reddit using Revancify under Termux, selected 'disable-ads' patch, and Revancify downloaded the apk from APKMirror correctly, but soon the patch warns me with error ''_SEVERE: disable-ads failed: 
app.revanced.patcher.patch.PatchResultError: 'disable-ads' depends on 'DisablePiracyDetectionPatch' but the following error was raised: Failed to resolve PiracyDetectionFingerprint_'', the app could be installed and run, but still showing ads.

### Steps to reproduce

Step 1: Run Revancify under termux in non-root mode (revancify -n), update all resources.
Step 2: Select Patch App
Step 3: Select Sync-for-reddit
Step 4: Downloading and patching started
Step 5: Error in log, disable-ads patch not applied.

### Relevant log output

```shell
INFO: Reading dex files 
INFO: Decoding AndroidManifest.xml only, because resources are not needed 
INFO: Skipping change-package-name: Excluded by default 
INFO: Skipping enable-android-debugging: Excluded by default 
INFO: Skipping export-all-activities: Excluded by default 
INFO: Skipping predictive-back-gesture: Excluded by default 
INFO: Skipping remove-screen-capture-restriction: Excluded by default 
INFO: Skipping remove-screenshot-restriction: Excluded by default 
INFO: Skipping spoof-wifi-connection: Excluded by default 
INFO: Executing patches 
INFO: change-oauth-client-id succeeded 
SEVERE: disable-ads failed: 
app.revanced.patcher.patch.PatchResultError: 'disable-ads' depends on 'DisablePiracyDetectionPatch' but the following error was raised: Failed to resolve PiracyDetectionFingerprint
	at app.revanced.patcher.Patcher.executePatches$executePatch(Patcher.kt:312)
	at app.revanced.patcher.Patcher.access$executePatches$executePatch(Patcher.kt:38)
	at app.revanced.patcher.Patcher$executePatches$1.invokeSuspend(Patcher.kt:358)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlin.sequences.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at app.revanced.utils.patcher.PatcherKt.applyPatchesVerbose(Patcher.kt:84)
	at app.revanced.cli.patcher.Patcher.start$revanced_cli(Patcher.kt:19)
	at app.revanced.cli.command.MainCommand.run(MainCommand.kt:166)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at app.revanced.cli.main.MainKt.main(Main.kt:7)
INFO: Not compiling resources because resource patching is not required 
INFO: Writing modified dex files 
INFO: Aligning base.apk to base-Revanced_aligned.apk 
INFO: Signing base-Revanced_aligned.apk to base-Revanced_signed.apk 
INFO: Found existing keystore: revancify.keystore 
INFO: Copying base-Revanced_signed.apk to base-Revanced.apk 
INFO: Cleaned up cache directory 
INFO: Finished 



Variant: nonRoot
Arch: arm64-v8a
App: Sync-for-reddit vv23.06.30-1339
CLI: revanced-cli-v2.21.5-dev.2.jar
Patches: revanced-patches-v2.180.0.jar
Integrations: revanced-integrations-v0.111.1.apk
Patches argument: -i change-oauth-client-id
-i disable-ads
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Sherman-Liu** [comment]
I already tried several versions of the Sync for Reddit app, it appears that it's not a version related issue.

**Comment by kbexit** [comment]
> I already tried several versions of the Sync for Reddit app, it appears that it's not a version related issue.

I'm on version v23.05.03-17:18 and patched with Revanced Manager and I don't have this issue at all.

**Comment by Sherman-Liu** [comment]
> > I already tried several versions of the Sync for Reddit app, it appears that it's not a version related issue.
> 
> I'm on version v23.05.03-17:18 and patched with Revanced Manager and I don't have this issue at all.

I tried it with Revanced Manager, bug still exists.
![Screenshot_20230701_184301_app revanced manager flutter](https://github.com/revanced/revanced-patches/assets/11748513/4934a98a-dbf2-4fd4-9252-2cae53c0342e)

**Comment by antonywalker** [comment]
I'm also having this issue.

**Comment by noemartinez** [comment]
> > I already tried several versions of the Sync for Reddit app, it appears that it's not a version related issue.
> 
> I'm on version v23.05.03-17:18 and patched with Revanced Manager and I don't have this issue at all.

I also tried this version and indeed the patch succeeded, but the app still seems to have ads for me. Same for you @kbexit ?

**Comment by kbexit** [comment]
> > > I already tried several versions of the Sync for Reddit app, it appears that it's not a version related issue.
> > 
> > I'm on version v23.05.03-17:18 and patched with Revanced Manager and I don't have this issue at all.
> 
> I also tried this version and indeed the patch succeeded, but the app still seems to have ads for me. Same for you @kbexit ?

No I don't have any ads either. Odd that it's different for everyone lol. I'm also a long time pro user, not sure if that has to do with it? But I'm on regular for Vanced.

**Comment by Sherman-Liu** [comment]
> > > > I already tried several versions of the Sync for Reddit app, it appears that it's not a version related issue.
> > > 
> > > 
> > > I'm on version v23.05.03-17:18 and patched with Revanced Manager and I don't have this issue at all.
> > 
> > 
> > I also tried this version and indeed the patch succeeded, but the app still seems to have ads for me. Same for you @kbexit ?
> 
> No I don't have any ads either. Odd that it's different for everyone lol. I'm also a long time pro user, not sure if that has to do with it? But I'm on regular for Vanced.

'Pro' version means it's already ads free... What's to patch anyway?

**Comment by noemartinez** [comment]
Did you get a Pro APK somehow? I only see regular ones on APK Mirror.

**Comment by oSumAtrIX** [comment]
Reopen issue with reproduction steps using official tools

**Comment by Sherman-Liu** [comment]
> Reopen issue with reproduction steps using official tools

What do you mean by that? I already tried in https://github.com/revanced/revanced-patches/issues/2549#issuecomment-1615843844 , there's no 'reproduction steps', just do the patch like any other apps would give the same error.

**Comment by oSumAtrIX** [comment]
If there is no steps to reproduce the issue, then there isn't any issue. Open a new issue otherwise for tracking purposes as described above
