### ISSUE TITLE
bug(youtube): video-speed fails to patch if old-video-quality-menu is not included

### ISSUE THREAD

**Issue by Domiiniik** [ReVanced/revanced-patches-template#2602]
### Type

Error while patching

### Bug description

 Custom Video Speed patch fails to patch with 18.23.35.

### Steps to reproduce

Patch Youtube 18.23.35 with custom Video Speed Patch and observe failed patching result.

### Relevant log output

```shell
...
```

### Screenshots or videos

![Screenshot_20230708_145316](https://github.com/revanced/revanced-patches/assets/30195961/f21ab5ba-502f-42f1-8c2b-9a875cd7e185)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Domiiniik** [comment]
> It's an issue with the dependency declarations of the patches.
> 
> For now, include `old-video-quality-menu` and it'll patch successfully.

I do, in fact its one of my must have patches. Yet this issue still happening.

**Comment by oSumAtrIX** [comment]
I have already pushed a fix for this yesterday, it's staged in the dev branch

**Comment by oSumAtrIX** [comment]
Nevermind, odd, I pushed but I can't find the commit

**Comment by xDARKxDEVILx** [comment]
> Are you sure you included old-video-quality-menu?
> 
> The patch name was slightly changed.
> 
> I can reproduce the problem by patching with default, and adding `-e old-video-quality-menu`, so the problem is video-speed depends on bits of the patch but does not declare it as a dependency.

I have same problem with that 
1- i don't get more video speed options
2- i get the new video quality layout

I don't have this issue on my phone and everything is fine,  but when i sent the app to my tablet i get these issues and others too

Note that both more speed options and old quality layout patches are included and patched successfully on my phone the issue only exists for my tablet

**Comment by xDARKxDEVILx** [comment]
I was going to open an issue for this but i think it should be fixed in the next patches version so i don't know if i should anymore

**Comment by xDARKxDEVILx** [comment]
> Try patching 18.20.39 and see if the issue is fixed.

Is this for me?

**Comment by oSumAtrIX** [comment]
Open a seperate issue for tablet. Tablet layouts aren't handled yet by the patch.

**Comment by xDARKxDEVILx** [comment]
> > Is this for me?
> 
> Yes

Can you link me to a good guide for cli as i want to have two different YouTube revanced and i need cli to change package name, i don't want to ruin my working version

**Comment by oSumAtrIX** [comment]
Here: https://github.com/revanced/revanced-cli/tree/main/docs.

This is not a support place.
