### ISSUE TITLE
feat(youtube): option to turn off "swipe left or right to seek" feature

### ISSUE THREAD

**Issue by GKid94** [ReVanced/revanced-patches-template#2657]
### Type

Other

### Bug description

The swipe options are still showing in Revanced when disabled

### Steps to reproduce

Disable the swipe options in settings, play a video and swipe on it

### Relevant log output

```shell
/
```

### Screenshots or videos

![Screenshot_2023-07-19-11-37-46-655_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/00c06ef9-8004-4ea1-bf99-5e2fda4b1616)
![Screenshot_2023-07-18-11-32-09-839_app revanced android youtube](https://github.com/ReVanced/revanced-patches/assets/18757054/3a0693ce-f1b5-439b-9124-38f23169aa35)
![Screenshot_2023-07-19-11-37-56-814_com miui securitycenter](https://github.com/ReVanced/revanced-patches/assets/18757054/a212ba51-13ff-4f3c-876a-59fe640d7e25)
![Screenshot_2023-07-19-13-02-07-011_com android settings](https://github.com/ReVanced/revanced-patches/assets/18757054/53040a21-71a5-4ea5-bc67-c78ee261d81d)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by GKid94** [comment]
How can I disable it?

**Comment by oSumAtrIX** [comment]
Open a feature request

**Comment by GKid94** [comment]
Also add an option do disable the swipe to fullscreen on the video player

**Comment by GKid94** [comment]
@oSumAtrIX Can you reopen this please?

**Comment by oSumAtrIX** [comment]
No, open a patch request, not a bug report.

**Comment by GKid94** [comment]
@oSumAtrIX It has been changed to a feature request report above

**Comment by oSumAtrIX** [comment]
Changing the title doesn't change the label nor the description of the issue.
