### ISSUE TITLE
bug: YT Revanced stops playback after some time

### ISSUE THREAD

**Issue by NotDemonix** [ReVanced/revanced-patches-template#2791]
### Type

Other

### Bug description

While watching a video with yt revanced, it stops after some time (official app works fine)
Is this the end of useable YouTube experience?

### Steps to reproduce

Play any video
Wait for some time

### Relevant log output

```shell
Idk how
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by fenchai23** [comment]
> What version youtube did you patch, and when did you patch the app?
> 
> If you patched the app more than a few weeks ago then you are outdated.

whats the recommended yt version to patch atm?

**Comment by oSumAtrIX** [comment]
The one that ReVanced Manager suggests.

**Comment by dajotim937** [comment]
@oSumAtrIX I'm using recommended version and using both spoof patches: Client and App Version. Still has problem with playback after 1:10 mark on 2 different devices.

**Comment by oSumAtrIX** [comment]
Attach a recording that includes the full process of patching and displaying the error.

**Comment by dajotim937** [comment]
What do you mean "error"? There is no error, I patch apk, open it, open random video and on 1:10 video begins loading\buffering infinitely.

**Comment by fenchai23** [comment]
the same thing happened to me, I just used the latest version patcher recommended, and that got fixed

**Comment by dajotim937** [comment]
> try turning on incognito mode or using a different YouTube account.

Why would I? I use account for a reason, I don't want to transfer all info, likes, history view, playlists, etc from TWO account to new ones.

**Comment by NotDemonix** [comment]
I updated the manager and etc and it works now

**Comment by dajotim937** [comment]
> But Im likely wasting my time giving suggestions because you probably are using outdated patches and it will never work right.

Lmao.
