### ISSUE TITLE
ReVanced resets itself when switch to shorts.

### ISSUE THREAD

**Issue by LegendarySpinx** [ReVanced/revanced-patches-template#29]
Check this video :

https://user-images.githubusercontent.com/69076256/174075680-2bdd96a6-5624-4bbb-bb71-afc5cfe79b6c.mp4

**Comment by oSumAtrIX** [comment]
Disable patches until this error disappears to find the patch which causes this.

**Comment by AdishSagarawat** [comment]
Still continuing

**Comment by AdishSagarawat** [comment]
To reset

**Comment by AdishSagarawat** [comment]
??
Same problem still facing...

**Comment by oSumAtrIX** [comment]
> Disable patches until this error disappears to find the patch which causes this.

Do as suggested.
