### ISSUE TITLE
bug: Adding Change-package-name option crash the app due to following

### ISSUE THREAD

**Issue by dib12** [ReVanced/revanced-patches-template#2993]
### Type

Error at runtime

### Bug description

Change-package-name breaks apk due to classes.dex /smalifiles and settings_fragment.xml is not modifying according to package name in options.json 

Its keeps the REVANCED_PACKAGE_NAME = app.revanced.android.youtube

Apk id is changing successfully according to options.json.but those are not
Kindly check screenshot

### Steps to reproduce

Open app-revanced setting -crashing

### Relevant log output

```shell
No log
```

### Screenshots or videos

![IMG_20230916_095737_586](https://github.com/ReVanced/revanced-patches/assets/61652361/a0a3321a-c19f-401c-a024-03ca055a8d00)
![Screenshot_20230916-095345_Trebuchet](https://github.com/ReVanced/revanced-patches/assets/61652361/99376121-15b2-4489-ae1f-c663fba1dab5)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
The patch only changes the package name in the manifest file

**Comment by dib12** [comment]
@oSumAtrIX then remove it
Its useless.app crashes

Its works fine in revanced extended

**Comment by dib12** [comment]
@LisoUseInAIKyrios OK.
But its a issue in microg resources patch.
I had checked the inotia00 repo

**Comment by dib12** [comment]
@LisoUseInAIKyrios 

https://github.com/inotia00/revanced-patches/blob/4d2fd8ff06808851cdfa4b71443e6a04246d0cb5/src/main/kotlin/app/revanced/patches/shared/patch/packagename/PackageNamePatch.kt#L4

**Comment by dib12** [comment]
@LisoUseInAIKyrios ahok
I will do the manual way f.ine when I changes in https://github.com/ReVanced/revanced-patches/blob/fbf72b767782f99cd846a9ee19c10756687daf0c/src/main/kotlin/app/revanced/patches/youtube/misc/microg/shared/Constants.kt#L5
And generate own patches.jar
