### ISSUE TITLE
bug: Reddit app is crashing when viewing posts (root)

### ISSUE THREAD

**Issue by dundunn** [ReVanced/revanced-patches-template#3202]
### Bug description

The patched app is just crashing when viewing every post. 

Steps I did:
- Uninstalled old patched Reddit
- Installed Reddit app via Google Play
- Cleared the storage of the Reddit app
- Patched it 

I can't test the normal installation because it's currently not possible to install it the normal way with the recent Google Play Protect update. 

### Error logs

```shell
https://paste.crdroid.net/21wRgY
```

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Google Play does not prevent you from installing apps. Not sure why patching Reddit with root fails, when the split APK versions match, in any case not a patches issue, use a full APK.

**Comment by dundunn** [comment]
At least it's preventing me from patching the app in normal mode. I can hit "Install anyway" but the update process doesn't seem to continue. The app still shows ads, which it doesn't in the rooted mode. 

What part of ReVanced is causing this issue? I don't really want to download a patched APK.

**Comment by oSumAtrIX** [comment]
> At least it's preventing me from patching the app in normal mode

That is not true, Play Protect will not prevent you.

**Comment by dundunn** [comment]
https://streamable.com/dug8s6
It seems Play Protect isn't working properly. It's probably an issue with the Gapps and the recent update I did. I'm gonna try to purge Gapps completely before sideloading it fresh.

**Comment by oSumAtrIX** [comment]
You are installing a split APK when you need a full one, and you have the unpatched app installed, so the signatures mismatch after patching.

**Comment by dundunn** [comment]
I don't follow, when I search for Reddit full apk I just find a lot of sketchy looking sites. Am I supposed to download the Reddit APK from a mirror like APKMirror?

**Comment by dundunn** [comment]
Isn't it supposed to give me a warning prior to updating the APK when it's supposed to be a split APK? It's the exact same behavior with the APK from APKMirror. You are really sure this can't be an issue with Google Play? It's only the Reddit app that behaves like this, YouTube and Boost are both fine, but I can't use normal mode on them either, only root.

**Comment by oSumAtrIX** [comment]
> supposed to give me a warning

no

> You are really sure this can't be an issue with Google Play

yes

**Comment by dundunn** [comment]
But what do you mean with full APK? I've downloaded older versions of Reddit and it's always the same. Patching it via root makes the app unusable because some attribute in some XML file is missing.

**Comment by dundunn** [comment]
And what makes you so sure it's no Play issue? It's not updating the app after I hit "Install anyway" so it's either ReVanced or Play that isn't working properly here. If it's not an issue with the patch, what is causing this issue then?

**Comment by oSumAtrIX** [comment]
> its not updating the app after I hit "Install anyway" so it's either ReVanced or Play that isn't working properly here.

Like I said before, the signatures missmatch. 
This is not a support thread. Move to other places for support.
