### ISSUE TITLE
feat: AI Features

### ISSUE THREAD

**Issue by fire17** [ReVanced/revanced-patches-template#3362]
### Feature description

Choose model api,
Add your key, 
& Start asking questions about videos! Get fast answers from a specific video or run a deep search across a playlist, history, your favorite channel, or even global search results. Find exact timestamps that explain or show what you are looking for, and get collective insights from multiple sources.

Basic route (Video)
-> watch a video -> click the AI Button -> get captions -> start asking questions about the video (include timestamps from  video in answer)

List route (Playlists/Watch History)
From List -> ask a general question -> scan watch history/playlist for relvant videos ->  rank videos by metadata (views desc rating etc) -> take captions of the most ranked videos and try to answer the query based on each -> sum up all the answers, identify final optimal response and return to user with information and collective insights (including referencing videos with timestamps)

Search route (in general search)
 -> ask a general question (from search, not a video) -> have model propose several good search queries -> run searches -> rank videos by metadata (views desc rating etc) -> scan watch history for relvant videos already watched and add ranking -> take captions of the most ranked videos and try to answer the query based on each -> sum up all the answers, identify final optimal response, and return to user with information (including referencing videos with timestamps)

This would be insane for uptodate deep research queries) as well as everyday youtube usage

### Motivation

I really believe that open source will be the driving force in providing the best features to the market
I would not wait for google to release AI Features to YT (and you know they'll do it for premium users only)

The hardest thing in this feature is the YT integration; all the rest is pretty much solved nowadays
So i'd love to partner up with a collaborators that has experience making revanced patches and would like to team up in creating this

I hope some people see the increadible value potential and revolution this can have
And honestly ask yourself, if you're like me, and just want to do this already on your own phone
Thanks a lot and all of the best!

### Acknowledgements

- [X] This issue is not a duplicate of an existing feature request.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by fire17** [comment]
@LisoUseInAIKyrios on the contrary, this MUST be run inside the main YT app
if not it's missing the point, I love and user ReVance for hours everyday, and shouldnt jump anywhere for this

Secondly, the hard part is not the ai feature, is to just add some buttons and panels to the YT app
some of the features are actually very easy and straight forward, i just lack the knowledge and experience of moding YT
So since i cant do this alone i ask for help from those experienced in this, ill take care of the ai features (foss)
please reconsider @LisoUseInAIKyrios and open this, so other contributors who are interested could potentially find and team up with me
thanks a lot and all the best :)

**Comment by oSumAtrIX** [comment]
The request you gave works nicely in a separate dedicated app. If you want this in the YouTube app ask YouTube not us.
