### ISSUE TITLE
 error of reducing video quality and not displaying the quality selection bar

### ISSUE THREAD

**Issue by lequangcuong123** [ReVanced/revanced-patches-template#3447]
![IMG_20240818_234136](https://github.com/user-attachments/assets/b06b9e76-3095-440a-a9bd-0d10df75d5bb)
![IMG_20240818_234436](https://github.com/user-attachments/assets/918f7ff1-3b5a-4817-b2ca-935812f29c05)
First, I'm sorry because what I say below may not be relevant to you. What I am talking about is the revanced extended application of no name exe 
https://github.com/NoName-exe/revanced-extended/releases
But since I can't report the error to him, I can only borrow it here to ask you to inform him.
I open any video and choose 720p - 1080p quality. At first, the video seemed normal, but after a few minutes, the video had trouble playing. It keeps reloading for a long time. Finally, it reduces the quality to the lowest level and also removes the display quality selection bar. This error only went away temporarily when I switched to another video and it persisted even after that. I tried downloading the latest version of revanced extended and the vanced microg version that comes with it but they don't work, I also tried turning off some options that could cause errors in the settings but couldn't solve the problem
Sorry for the inconvenience and thanks for reading

**Comment by oSumAtrIX** [comment]
Unofficial patches

**Comment by lequangcuong123** [comment]
> Unofficial patches & wrong repository

I used that version a long time ago on root and without root and didn't notice any problems, but recently there have been problems with the non-root version

**Comment by oSumAtrIX** [comment]
For support, move to one of our links at https://revanced.app.

**Comment by lequangcuong123** [comment]
> Still, unofficial patches and wrong repo. For support, move to one of our links at https://revanced.app.

I get it, ty
