### ISSUE TITLE
bug: `buildDexJar` fails on Windows

### ISSUE THREAD

**Issue by Ushie** [ReVanced/revanced-patches-template#3450]
### Bug description

The `buildDexJar` task fails in two steps:

- Fails to find d8 in android build-tools
- Adding classes.dex to the archive

### Solution

d8 has the .bat extension and it ends up not resolving, maybe you could ignore the file extension

As for classes.dex, the zip command doesn't exist on Windows, it might be better to use a Kotlin solution to add the dex to the archive

### Acknowledgements

- [X] I have checked all open and closed bug reports and this is not a duplicate.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
Such task doesn't exist. "buildAndroid" does & it comes from the gradle plugin for patches
