### ISSUE TITLE
feat: ci to generate .json file containing remote link of assets

### ISSUE THREAD

**Issue by indrastorms** [ReVanced/revanced-patches-template#3452]
### Feature description

ci to generate .json file containing remote link of assets

### Motivation

1. To add third party bundle easily in revanced manager (compose)
2. Third party patches can be auto updated

### Acknowledgements

- [x] I have checked all open and closed feature requests and this is not a duplicate
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
The official method to provide patches to manager is via the api

**Comment by indrastorms** [comment]
> The official method to provide patches to manager is via the api

What about third party patches?

**Comment by oSumAtrIX** [comment]
Same for them. They officially are supposed to supply patches via the api. Manager is an API client. Of course they can also statically generate the response unofficially

**Comment by indrastorms** [comment]
> Same for them. They officially are supposed to supply patches via the api. Manager is an API client. Of course they can also statically generate the response unofficially

I'm asking for compose rewrite manager where it can take multiple patches source and patch at the same time.
api can't supply multiple patches so an alternative remote method is required for sourcing patches.

**Comment by oSumAtrIX** [comment]
You would enter the API url in the field when adding the remote source.

**Comment by indrastorms** [comment]
> You would enter the API url in the field when adding the remote source.

What's about multiple sources?

**Comment by oSumAtrIX** [comment]
This is multiple sources.

**Comment by indrastorms** [comment]
> This is multiple sources.

Please tell me the procedure how to patch an app with patchs from revanced (patch a, b) and pico (patch c, d) in one go like cli
Cli only support local files but in manager we want remote file for auto update

**Comment by oSumAtrIX** [comment]
They host the patches via the API, you add the URLs to manager and done

**Comment by indrastorms** [comment]
> They host the patches via the API, you add the URLs to manager and done

So you want us to host official files and 3rd party files in a server?

**Comment by oSumAtrIX** [comment]
That's right. The API handles supply.

**Comment by indrastorms** [comment]
> That's right. The API handles supply.

Its impractical to rent a server for some small patches.
Why are you against what compose manager currently can do is take a json file and download file specified in the json file.

**Comment by oSumAtrIX** [comment]
Refer to:

> Of course they can also statically generate the response unofficially

**Comment by indrastorms** [comment]
> Refer to:
> 
> > Of course they can also statically generate the response unofficially

So my request is to generate that json file with ci

**Comment by oSumAtrIX** [comment]
You ca do that. Refer to:
> unofficially

**Comment by indrastorms** [comment]
> You ca do that. Refer to:
> 
> > unofficially

Why not making it mainstream?

**Comment by oSumAtrIX** [comment]
Because it's not elegant and impractical. If the API changes you also have to sync your unrelated CI. Also, for "small patches" you can add the patches locally. Anything beyond that should be done in a streamlined manner via the API

**Comment by indrastorms** [comment]
> Because it's not elegant and impractical. If the API changes you also have to sync your unrelated CI. Also, for "small patches" you can add the patches locally. Anything beyond that should be done in a streamlined manner via the API

Changes for these api gonna be very rare, so not an issue compared to patcher api changes.
We need  to constantly update the json every release so manually doing it is a headache.

**Comment by oSumAtrIX** [comment]
Therefore you use API. If you can't, then you can mimick it unofficially 

Ussing a CI to generate static JSON files duplicates functionality that the API already provides.  The API is a standardized way for distributing patches. Using a static JSON approach makes the workflow more fragmented.

**Comment by indrastorms** [comment]
Thanks, i will make my own workflow 😐
With help of chatgpt 😂
