### ISSUE TITLE
bug: Wide searchbar doesn't work

### ISSUE THREAD

**Issue by TheMerret** [ReVanced/revanced-patches-template#372]
### Type

Cosmetic

### Bug description

wide searchbar can't be enabled.

### Steps to reproduce

1. Apply relevant patch
2. Enable in settings
3. Reopen app
4. Searchbar isn't wide 

### Relevant log output

```shell
?
```

### Solution

Maybe [this](https://github.com/revanced/revanced-patches/blob/v2.41.0/src/main/kotlin/app/revanced/patches/youtube/layout/widesearchbar/patch/WideSearchbarPatch.kt#L42) needs to be true by default

### Additional context

cli v2.93
patches v2.41.0
youtube v17.32.35

**Comment by oSumAtrIX** [comment]
The exception is unrelated but tmwide searchbar indeed does not work.

**Comment by XBadFellaX** [comment]
I am having the same issue when buidling with v2.41.0.

Downgraded to my build with v2.39.1 and everything works fine there.

**Comment by TheMerret** [comment]
> The exception is unrelated
yep, i missed, sorry.
But as i see there is no log messages in wide searchbar patch

**Comment by XBadFellaX** [comment]
> Not working for me

Try Version v17.32.38(Stable) with Patches 2.39.1.

**Comment by TheMerret** [comment]
> Try Version v17.32.38(Stable) with Patches 2.39.1.

Hm, same, not working.

**Comment by tzuyu18** [comment]
I have this issue also.
YT v17.32.35
Patch 2.42.0

**Comment by oSumAtrIX** [comment]
Fixed.
