### ISSUE TITLE
feat(youtube): add a playback seekbar to Shorts

### ISSUE THREAD

**Issue by MatadorProBr** [ReVanced/revanced-patches-template#491]
### Application

YouTube

### Issue

Can't skip to some part of the shorts without having to rewatch.

### Patch

A patch that adds a seekbar and allows anyone to skip to some part of the video they want to rewatch (like the tiktok-seekbar patch but for YouTube).

### Motivation

Because people don't want to spend their time having to rewatch the entire shorts just to see a little part that they wanna see again. Probably not too much since not much people care about YT Shorts (I guess).

**Comment by aviv926** [comment]
Any new update on this?

**Comment by oSumAtrIX** [comment]
Btw, iOS has this for a longer time (at least on ipads)
