### ISSUE TITLE
Feature Request: Youtube Revanced for Android TV Support

### ISSUE THREAD

**Issue by briantho** [ReVanced/revanced-patches-template#559]
### Application

Add support for youtube for android TV

### Issue

Currently there is no good way to block ads, or have sponserblock on youtube for android tv

### Patch

I would like to see full support for android tv. That means revanced manager for android tv and youtube revanced for android tv. I would like to see sponsorblock, full casting support, and of course ad blocking supported in the youtube app for android tv. My goal is to be able to cast youtube from the youtube revanced app on my phone to my chromecast with google tv, and have no ads, and sponsorblock enabled. 

### Motivation

IMHO, there really isn't a good way for android tv devices such as the chromecast with google tv, to have the full revanced feature set. I'm aware there are apps like smarttubenext, and whatnot, but there are a number of features missing from them. For instance one cannot do true casting to smarttubenext, instead you have to input a code generated from smarttube next for the youtube app on your phone to find it. There are a number of problems with this approach, as not only is it considered legacy, but it does not work for programs like chrome, or youtube music. Anyway, I would really like support for patching the real youtube app on android tv.

**Comment by bozander** [comment]
For Android TV you can use SmartTubeNext https://smartyoutubetv.github.io/ru/

**Comment by briantho** [comment]
yes, i know that. However it doesn;t support the full feature set of youtube revanced, not does it support true casting. The biggest downside of that app for me is the casting support. It does not work for apps like youtube music, or for desktop apps like chorme. For me smarttubenext is just not worth it.

**Comment by briantho** [comment]
why was this closed?

**Comment by oSumAtrIX** [comment]
It's a web app not dalvik.

**Comment by its0x08** [comment]
Actually would be extremely useful if the tv app for youtube had no ads!
Lets take a vote.
