### ISSUE TITLE
bug: swipe-control not following device volume

### ISSUE THREAD

**Issue by kazimmt** [ReVanced/revanced-patches-template#634]
### Type

Cosmetic

### Bug description

Currently, 100% volume on youtube rv swile control = 66% on device
150% on yt rv = 100% on device

It's weird
It should rv 100%=100% on device

Device: PocoF3 (Memeui)

### Steps to reproduce

1. Enable swipe control
2. Play a video
3. Make it full screen
4. Increase volume to 100% using swipe
5. Back to normal screen
6. Press volume rocker
7. You'll see it's not 100%

### Relevant log output

```shell
N/A
```

### Screenshots or videos

![Screenshot_2022-09-26-20-48-17-789_app revanced android youtube](https://user-images.githubusercontent.com/82371061/192320743-f2bf2169-4b40-4d30-8462-dd68710e318d.jpg)
![Screenshot_2022-09-26-20-48-10-664_app revanced android youtube](https://user-images.githubusercontent.com/82371061/192320768-2108acb0-341f-4a81-b45e-367938606a30.jpg)
![Screenshot_2022-09-26-20-47-28-214_app revanced android youtube](https://user-images.githubusercontent.com/82371061/192320772-e4adc0ae-4376-4fe2-9132-225d76f4c055.jpg)

### Solution

Swipe control should follow volume rocker
100% on swipe control = 100% on device volume

### Additional context

@shadow578 i think you can fix it. As it implemented by you.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by shadow578** [comment]
this isn't a bug. 
the volume level isn't shown in percent, but in volume steps. 
on most devices, the volume will only go to maybe 25 (as there are only 25 volume steps), but on your device theres 150 steps.

**Comment by kazimmt** [comment]
@shadow578 thanks for the reply & its correct. 
I found 150 steps on my volume & edit it to 25 (using module)
Now max volume showing on swipe-control is also 25.

Thanks again

**Comment by ramuskentas** [comment]
> 

Hey, can you tell me which module have you used? Mine xiaomi have the same problem

**Comment by clicky6** [comment]
> @shadow578 thanks for the reply & its correct. I found 150 steps on my volume & edit it to 25 (using module) Now max volume showing on swipe-control is also 25.
> 
> Thanks again

Which module did you use, I also have 15 volume steps as of now, How do I make them 100 or 150 in volume swipe controls in ReVanced?

**Comment by oSumAtrIX** [comment]
No, it would jump between values in the range of 100 because of the step size

**Comment by oSumAtrIX** [comment]
No, as explained [here](https://github.com/ReVanced/revanced-patches/issues/634#issuecomment-1259854920).

**Comment by clicky6** [comment]
> No, as explained [here](https://github.com/ReVanced/revanced-patches/issues/634#issuecomment-1259854920).

Then How LibreTube is doing it?

And above someone used some module to change it, Can you guide me on that, Which module is it, How to install it and how to change the volume steps.
