### ISSUE TITLE
Home Page Ads

### ISSUE THREAD

**Issue by killerlearner** [ReVanced/revanced-patches-template#731]
### Type

Other

### Bug description

From some time my yt vanced vanced showing ads on homepage and yeah I have disabled ads from homepage in setting. And the ads showing from some time now like patcher manager got update 2 times but still didn't solved. And back to close app is also there.

### Steps to reproduce

Install these patches and apply then you will find home page ads still popping up there
![Screenshot_2022-10-07-15-55-50-856_app revanced manager flutter](https://user-images.githubusercontent.com/67904798/194532964-055bcd87-9652-4106-92a5-9a4ef88c8dad.png)

### Relevant log output

```shell
No Log
```

### Screenshots or videos

![IMG_20221007_155810](https://user-images.githubusercontent.com/67904798/194533215-346b8f18-b51b-4a36-bc55-34bcb2605120.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Update and repatch.

**Comment by killerlearner** [comment]
> Update and repatch.

What update i updated manager many times 😑

**Comment by oSumAtrIX** [comment]
I can clearly see you last patched September: 
![image](https://user-images.githubusercontent.com/13122796/194534870-f2806c3f-ab37-41b2-a2be-4a9d508658df.png)
