### ISSUE TITLE
feat(patch):patch request: destraction free youtube

### ISSUE THREAD

**Issue by snoobysnoofy** [ReVanced/revanced-patches-template#739]
### Application

removes all the videos from the home page of the youtube, just a blank screen.

### Issue

youtube wants us to be on there app/site for long time, it keeps recommending cheesy or short funny videos, which distracts me, and I start watching that videos(or at least it deviates my mind). and that is not the main reason I open youtube for. It leads wasting of my time.

### Patch

I want to see just a blank screen when I open youtube, and a search bar. so I can directly search on youtube, and watch the thing which I opened youtube for, without any distraction, or remove the home feed section completely.

### Motivation

There is very popular extension for browser which provides this functionality. 

![image](https://user-images.githubusercontent.com/114791490/194715783-001df1c0-7335-41ef-8ba5-07f0aee4f138.png)

this feature will be very helpful for students and it will save lots of their time, and they can focus on the things they want to. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by rohan2000github** [comment]
If someone wants this kind of feature then it is a good idea to just simply use newpipe or libretube like alternatives

**Comment by swarnenduu** [comment]
@snoobysnoofy I also agree with you. As a student, what you described is very distracting. 
@rks2000 I have used libretube and newpipe, but these are apps that don't allow you to comment on videos which is very much required when watching live classes. Moreover no app can match the fluidity and ui of the YT app.

I think this patch is very much needed

**Comment by rks2000** [comment]
> @snoobysnoofy I also agree with you. As a student, what you described is very distracting. @rks2000 I have used libretube and newpipe, but these are apps that don't allow you to comment on videos which is very much required when watching live classes. Moreover no app can match the fluidity and ui of the YT app.
> 
> I think this patch is very much needed

If you really want to use this feature. I would suggest you to use Revanced Extended by inotia00

**Comment by swarnenduu** [comment]
> > @snoobysnoofy I also agree with you. As a student, what you described is very distracting. @rks2000 I have used libretube and newpipe, but these are apps that don't allow you to comment on videos which is very much required when watching live classes. Moreover no app can match the fluidity and ui of the YT app.
> > I think this patch is very much needed
> 
> If you really want to use this feature. I would suggest you to use Revanced Extended by inotia00

I was unable to locate any app under release section of the repository. Could you please help me out with the link to ReVanced extended.

**Comment by rks2000** [comment]
> > > @snoobysnoofy I also agree with you. As a student, what you described is very distracting. @rks2000 I have used libretube and newpipe, but these are apps that don't allow you to comment on videos which is very much required when watching live classes. Moreover no app can match the fluidity and ui of the YT app.
> > > I think this patch is very much needed
> > 
> > 
> > If you really want to use this feature. I would suggest you to use Revanced Extended by inotia00
> 
> I was unable to locate any app under release section of the repository. Could you please help me out with the link to ReVanced extended.

https://github.com/inotia00/rvx-builder/wiki/How-to-use-rvx-builder-on-Android

Folows the steps to patch the app by yourself using builder in termux

**Comment by rks2000** [comment]
> > > @snoobysnoofy I also agree with you. As a student, what you described is very distracting. @rks2000 I have used libretube and newpipe, but these are apps that don't allow you to comment on videos which is very much required when watching live classes. Moreover no app can match the fluidity and ui of the YT app.
> > > I think this patch is very much needed
> > 
> > 
> > If you really want to use this feature. I would suggest you to use Revanced Extended by inotia00
> 
> I was unable to locate any app under release section of the repository. Could you please help me out with the link to ReVanced extended.

https://t.me/revanced_extended_chat join this group for more help related to this

**Comment by swarnenduu** [comment]
The repository has been archived. What if I face any issue? I wouldn't be able to raise a issue then.

**Comment by rks2000** [comment]
> The repository has been archived. What if I face any issue? I wouldn't be able to raise a issue then.

Join the above group if you face any issue.
Also His work is being continued by the other person named YT-Advanced https://github.com/YT-Advanced/ReX-patches

But for me inotia00 version is currently working fine. So i didn't switch for now

**Comment by swarnenduu** [comment]
Thanks. I was unable to install rvx builder using termux. I followed the instructions but something's not right.

**Comment by swarnenduu** [comment]
![Screenshot_20230828-151112-114](https://github.com/ReVanced/revanced-patches/assets/86847643/a7ca3dd7-e5a9-4cd6-8316-26b050a92ac6)

**Comment by swarnenduu** [comment]
Wait I tried vpn and the termux proces is working

**Comment by rks2000** [comment]
But You should also give this revancify a try its really good tool to have

**Comment by swarnenduu** [comment]
Will check out for sure @rks2000
