### ISSUE TITLE
bug: videos skipping back a few seconds when watching videos (video ads patch)

### ISSUE THREAD

**Issue by nummer-GDD** [ReVanced/revanced-patches-template#752]
### Type

Error at runtime

### Bug description

this seems to happen every time an ad is supposed to play, but got removed by the patch. the ad is removed, but not the skip back in time.

### Steps to reproduce

1. patch youtube with the video ads patch
2. watch a video with mid-roll ads
3. when an ad is supposed to play, the video will not play the ad, but do the skip back in time that comes with the ad.

### Relevant log output

```shell
n.a.
```

### Screenshots or videos

https://streamable.com/0a91c1
note that the transition to black is part of the video.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by antakor** [comment]
I can confirm this happening. It seems to have been introduced in patch version 2.81.1. I did not have this behavior before repatching with this version. Using the recommended version of the youtube app

**Comment by oSumAtrIX** [comment]
Can you check if this was fixed by commit e353ed0b0fe78feae65f1ad2f6567c1e9aa9c71d?

**Comment by AMSAMSAMSAMS** [comment]
not fixed... still here...
I thought I was going insane before reading this lol....

**Comment by nummer-GDD** [comment]
as of now when an ad is supposed to play the video buffers only for a split second

**Comment by jonas-hurst** [comment]
It seems like this is also related to https://github.com/revanced/revanced-patches/issues/749#issuecomment-1274641355
Whenever the mid-video ad is supposed to play, brightness is reset to system default.

**Comment by arDrag0n** [comment]
Experiencing the same bug

**Comment by binge-coder** [comment]
have the same bug and its driving me crazy at this point.

**Comment by Matty003** [comment]
I experienced this issue today when watching a video. It went 10 seconds back when moving to next chapter .

**Comment by Matty003** [comment]
I experienced this issue today when watching a video. It went 10 seconds back when moving to next chapter .
Patches Ver. 2.81.11

**Comment by Matty003** [comment]
> Can you check if this was fixed by commit [e353ed0](https://github.com/revanced/revanced-patches/commit/e353ed0b0fe78feae65f1ad2f6567c1e9aa9c71d)?

I experienced this issue today when watching a video. It went 10 seconds back when moving to next chapter .
Patches Ver. 2.81.11

**Comment by oSumAtrIX** [comment]
Temporal fix with commit 7aa3bce6ccd669a66de10ef6ffe2151f27b40365.
