### ISSUE TITLE
feat(patch): Bring back old trending page button.

### ISSUE THREAD

**Issue by Arunkapil01** [ReVanced/revanced-patches-template#835]
### Application

Youtube

### Issue

Sometimes the explore button just hides away and there is no way to bring it back. Also, I don't use and like shorts. So, it would be better to bring back the old better button.

### Patch

A button replacing the shorts button. Which opens feeds/trending page, instead of shorts.

### Motivation

It helps those who want to old trending button back from good old youtube.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
You can already do that by opening it from the chip bar at the top.

**Comment by Arunkapil01** [comment]
I can't

**Comment by Arunkapil01** [comment]
![Uploading Screenshot_20221022-134040.jpg…]()

**Comment by Arunkapil01** [comment]
> You can already do that by opening it from the chip bar at the top.

https://media.discordapp.net/attachments/1033292494567395408/1033292494877765672/Screenshot_20221022-134040.jpg

**Comment by oSumAtrIX** [comment]
Disable patches until the error is gone, report back which one caused it.

**Comment by Arunkapil01** [comment]
> Disable patches until the error is gone, report back which one caused it in a new issue.

It doesn't works lmao. There is no way to bring it back that way. You said i have to feature request here

**Comment by oSumAtrIX** [comment]
The feature exists as previously mentioned, do what i suggested.
