### ISSUE TITLE
Videos not reliably loading for UK YouTube users

### ISSUE THREAD

**Issue by EvilBadger** [ReVanced/revanced-patches-template#838]
### Type

Error at runtime

### Bug description

When trying to watch YouTube videos in the UK ~1/4 of the videos I try and play get stuck "loading" / "buffering" indefinitely and will never start playing on their own. 
You can work around this buy skipping to the end of the video then using replay to restart playback which will start immediately. You can also use a VPN to load videos while connected to US server. 

### Steps to reproduce

1. Live in the UK / connect to UK VPN server 
2. Try playing multiple videos
3. Video will get stuck loading 

### Relevant log output

```shell
N/A
```

### Solution

You can work around this buy skipping to the end of the video then using replay to restart playback which will start immediately. You can also use a VPN to load videos while connected to US server. 

### Additional context

This issue seems to have started to occur when YouTube UK started to block my old vanced app telling me I needed to upgrade the app to play videos.

ReVanced/revanced-patches-template#2078 - Related bug that has been closed but issue remains.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MrMikeJJ** [comment]
I get this on all videos, not just a 1/4 of them. Also in the UK. I also use the work around, where i skip the video to the end and press repeat.

**Comment by BeefSteaker** [comment]
Closer to 75% of vids

**Comment by EvilBadger** [comment]
I wonder if this is related to which isp and then what YouTube server you hit as they are rolling out these changes? 

swapping region using the VPN instantly fixes is but I'm going to imagine that will only work until YT do a full rollout of changes?

**Comment by scottyell** [comment]
I'm also experiencing this, most videos refuse to play the first time

**Comment by amazingakita** [comment]
can confirm this is still happening for me, using revanced patch 2.85.2 on youtube 17.36.37

**Comment by oSumAtrIX** [comment]
The ad has nothing to do with the device. It is a regional A/B issue.

**Comment by plexay** [comment]
UK here also get this issue, manual installed perfectly multiple times, many versions. always happens. will try us VPN and let you know if it works but It's on every video, some will load 5s then stop:/ fucking awful

**Comment by TheMaskedAvengers** [comment]
Same problem...also in the UK!

For me 90% of vids affected. Also can get round it by closing video and immediately reopening agaun or by clicking for the next video then going back. Interestingly if you click next video the next video always plays flawlessly as does the original if you go back....

On one occasion I think I caught a fleeting glimpse of a skip add button just before the endless loading started.

**Comment by Al-1A** [comment]
I'm affected too... It (the video ) stops & starts buffering when the video playback reaches 9/10 seconds as a workaround I close the video & restart it again.

**Comment by TheMaskedAvengers** [comment]
Same symptoms here.  Also in UK. Solved by VPN. Non root using microG android 11.  Closing the video and reopening it resumes playback as does using overlay controls to pick next video then going back to the original video.

**Comment by TheMaskedAvengers** [comment]
I'm posting with data sincerely trying to help and it's being marked as spam - inaccurate and hurtful.

UK based. Same issue as stated in erroneously flagged messages. 90% videos affected. Fixed by VPN. Work around is close and restart videos.

Android 11. Nonroot with MicroG. Works with any non UK VPN endpoint.

Please don't flag this message as spam. It isnt. Trying to help the devs narrow this down and confirming there's an issue.

Can prob be reproduced by connecting via a UK VPN endpoint and trying the app I'd imagine.

**Comment by oSumAtrIX** [comment]
Your information is already posted on this issue and flagged as spam numerous times.

**Comment by oSumAtrIX** [comment]
Temporal fix with commit 7aa3bce6ccd669a66de10ef6ffe2151f27b40365.
