### ISSUE TITLE
feat(patch): Frame skipping buttons

### ISSUE THREAD

**Issue by buddyjojo** [ReVanced/revanced-patches-template#851]
### Application

Youtube

### Issue

Sometimes youtube videos have text or very quick events that require rapid pausing to see, so this will allow frame by frame viewing to make that much easier. 

### Patch

Two buttons somewhere (I'm not a designer) that allows skipping forward and backwards frame by frame. (like the < > buttons on desktop) 

### Motivation

Again, allows easier viewing of single frame events. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
For that buttons already exist in the SponsorBlock popup panel.

**Comment by buddyjojo** [comment]
I feel this would be better as a separate patch.
Personally I don't use SponsorBlock and using that patch only for this would be a bit much yknow.

**Comment by buddyjojo** [comment]
Ok using the buttons from a unrelated feature (that popup panel is meant for segment adding) of a plugin I don't even use and others probably don't is not ideal at all.

I would at least like a better explanation or the opinion of another dev instead of this being immediately closed.

**Comment by oSumAtrIX** [comment]
There is no other maintainer of the patches except me. Include the SponsorBlock patch and disable all segments, then use the overlay buttons.
